apiVersion: v1
kind: ConfigMap
metadata:
  name: cicd-registry-configs
  labels:
    {{- include "registry.labels" . | nindent 4 }}
binaryData:
  config.yml: |-
    {{- toYaml .Values.configuration | b64enc | nindent 4 }}
