apiVersion: v1
kind: Secret
metadata:
  name: cicd-registry-docker-config-secret
  labels:
    {{- include "registry.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    ewogICAgImF1dGhzIjogewogICAgICAgICJjaWNkLXJlZ2lzdHJ5IjogewoKICAgICAgICB9CiAgICB9Cn0=